import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Configuration de la barre latérale du Wiki 3LEvent.
 * Le mode 'autogenerated' crée automatiquement le menu basé sur ton dossier /docs
 */
const sidebars: SidebarsConfig = {
  // Génère la structure automatiquement à partir du dossier docs/
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Scanne tout le dossier docs
    },
  ],

  /* Si tu veux un jour trier manuellement, tu pourras utiliser cette syntaxe :
  wikiSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Infrastructure',
      items: ['serveur/installation', 'serveur/configuration'],
    },
  ],
  */
};

export default sidebars;